// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMxi8_XDVFhmXxGN5sUmB9JwN8wHrs15Y',
    appId: '1:157883940682:web:bf0bc3db5b31848c27cbb3',
    messagingSenderId: '157883940682',
    projectId: 'medrepsubscription',
    authDomain: 'medrepsubscription.firebaseapp.com',
    storageBucket: 'medrepsubscription.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7a7bbme80EeOvyrrQ6naxMBlFb9Jibk',
    appId: '1:157883940682:android:763b24bc87fbba3327cbb3',
    messagingSenderId: '157883940682',
    projectId: 'medrepsubscription',
    storageBucket: 'medrepsubscription.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7njfr9LXFZ9y__LnAygzO2W85l351eL8',
    appId: '1:157883940682:ios:c9f56c9faab112be27cbb3',
    messagingSenderId: '157883940682',
    projectId: 'medrepsubscription',
    storageBucket: 'medrepsubscription.firebasestorage.app',
    iosBundleId: 'com.enrique.imageFolderViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7njfr9LXFZ9y__LnAygzO2W85l351eL8',
    appId: '1:157883940682:ios:e6cf2a559fb53ee027cbb3',
    messagingSenderId: '157883940682',
    projectId: 'medrepsubscription',
    storageBucket: 'medrepsubscription.firebasestorage.app',
    iosBundleId: 'com.example.imageFolderViewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMxi8_XDVFhmXxGN5sUmB9JwN8wHrs15Y',
    appId: '1:157883940682:web:dc5adf75977c281627cbb3',
    messagingSenderId: '157883940682',
    projectId: 'medrepsubscription',
    authDomain: 'medrepsubscription.firebaseapp.com',
    storageBucket: 'medrepsubscription.firebasestorage.app',
  );
}