platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. Run flutter pub get first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

      other_cflags = config.build_settings['OTHER_CFLAGS']
      if other_cflags.is_a?(Array)
        config.build_settings['OTHER_CFLAGS'] = other_cflags.reject { |f| f == '-G' }
      elsif other_cflags.is_a?(String)
        config.build_settings['OTHER_CFLAGS'] = other_cflags.split.reject { |f| f == '-G' }.join(' ')
      end

      other_cplusflags = config.build_settings['OTHER_CPLUSPLUSFLAGS']
      if other_cplusflags.is_a?(Array)
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = other_cplusflags.reject { |f| f == '-G' }
      elsif other_cplusflags.is_a?(String)
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = other_cplusflags.split.reject { |f| f == '-G' }.join(' ')
      end
    end
  end
end